# Generated by Django 3.2.5 on 2021-10-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCommentModel',
        ),
    ]
